- components/ColorSchemeToggle/ColorSchemeSwitch.tsx
- components/Settings/SettingsMenu.tsx
- components/layout/Header.tsx
- components/modules/calendar/CalendarModule.tsx
- components/modules/calendar/MediaDisplay.tsx
- package.json
- [Add darkmode switch in settings menu](https://github.com/ajnart/myhomepage/pull/25/commits/43c0465e52d162121a35ff76faed93ce6417a150) https://github.com/ajnart/myhomepage/issues/21
- [Update package.json](https://github.com/ajnart/myhomepage/pull/25/commits/a51cb5d777c5e394c9d799f0526ea315f0e84503)
- [Add the ability to display multiple medias released on the same day](https://github.com/ajnart/myhomepage/pull/25/commits/a2a3155081d6bf4fb8c7a7aa4aa8fdc220501fb3)
- [Use general media display component](https://github.com/ajnart/myhomepage/pull/25/commits/cb3abbc1c72253254c4ed818f6e67bf9bd68b810)
> Merge dev into master

- README.md
- components/AppShelf/AddAppShelfItem.tsx
- components/AppShelf/AppShelf.tsx
- components/AppShelf/AppShelfItemWrapper.tsx
- components/layout/Aside.tsx
- components/layout/Layout.tsx
- components/layout/Navbar.tsx
- components/modules/calendar/CalendarModule.tsx
- components/modules/calendar/MediaDisplay.tsx
- components/modules/date/DateModule.story.tsx
- components/modules/date/DateModule.tsx
- components/modules/moduleWrapper.tsx
- components/modules/modules.tsx
- package.json
- pages/_app.tsx
- tools/theme.ts
💃🏻 Style : 
- Better looking modules
- Added a module that displays the time and date
- Dark mode toggle is now in settings menu
- Better styling for the main app shelf
- Multiple medias can be shown on the same day
🧑🏻‍💻 Nerd stuff : 
- Automated docker image deployment to GitHub containers
- Code cleanup for easier module integration
- Added a box around each module with moduleWrapper
> Merge dev into master for v0.1.4

- README.md
> fix: Center align Discord CTA

- README.md
> 📝 Documentation
> The pull request adds documentation for volume mounting.
> ![image](https://user-images.githubusercontent.com/71191962/168332497-4c3a16cf-2b4c-430f-a0c1-d78ea8e7dde1.png)
> 📝 Adds documentation for volume mounting

- README.md
> 📝 Documentation
> This PR adds a known issues list to the README.md because people are ~~stupid~~ a bit silly. And don't know that the issues page exists.
> 📝 Adds known issues

- README.md
Added build status badges 
made image bit bigger
> :memo: Add build status badges

- .github/workflows/docker_dev.yml
- src/components/AppShelf/AddAppShelfItem.tsx
- src/components/AppShelf/AppShelf.story.tsx
- src/components/AppShelf/AppShelf.tsx
- src/components/AppShelf/AppShelfItemWrapper.tsx
- src/components/Settings/SettingsMenu.tsx
- src/components/layout/Footer.tsx
- src/components/layout/Header.tsx
- src/components/layout/Layout.tsx
- src/components/layout/Logo.tsx
- src/components/layout/Navbar.tsx
> ♿️ Work on responsiveness for the AppShelf

- src/components/SearchBar/SearchBar.tsx
> ✏️ Improves the searchbar tooltip

- README.md
> Documentation
> This PR updates the documentation to inform about Integrations, Multiple Configs, Icons, Modules, and Search Bar.
> 📝 Updates documentation

- .github/workflows/docker.yml
- .github/workflows/docker_dev.yml
- Dockerfile
> Build related changes 
[8054021 7cd74a2]Some files when updated don't need to cause the CI to run. Now they won't
[ec46369] Also removed unneeded files in the dockerfile
> 💚Stop running CI when files like readme.md are updated

- src/components/AppShelf/AppShelf.tsx
- src/components/modules/index.ts
- src/components/modules/ping/PingModule.story.tsx
- src/components/modules/ping/PingModule.tsx
- src/components/modules/ping/index.ts
- src/pages/[slug].tsx
- src/pages/api/modules/ping.ts
Resolves #78
Adds a module that pings the services and shows if they are up/down
> :sparkles: Add ping service module

- src/components/Settings/ModuleEnabler.tsx
- src/components/modules/date/DateModule.tsx
- src/components/modules/moduleWrapper.tsx
- src/components/modules/modules.tsx
- src/components/modules/ping/PingModule.tsx
- src/components/modules/search/SearchModule.tsx
- src/components/modules/weather/WeatherModule.tsx
- src/pages/[slug].tsx
- src/pages/index.tsx
- src/pages/tryconfig.tsx
- src/tools/state.tsx
- src/tools/types.ts
Should be WAAAAY easier to work with modules now
> :sparkles: Add new config format

- package.json
- src/components/AppShelf/AddAppShelfItem.tsx
- src/components/modules/downloads/DownloadsModule.tsx
- src/components/modules/downloads/TotalDownloadsModule.tsx
- src/pages/api/modules/downloads.ts
- src/tools/types.ts
- yarn.lock
> Transmission Integration

- src/components/AppShelf/AddAppShelfItem.tsx
- src/components/AppShelf/AppShelfItem.tsx
- src/components/AppShelf/AppShelfMenu.tsx
- src/tools/types.ts
> ✨ Add different URL for API calls

- src/pages/[slug].tsx
- src/pages/_app.tsx
- src/pages/_middleware.ts
- src/pages/api/configs/tryPassword.tsx
- src/pages/index.tsx
- src/pages/login.tsx
> ✨Password / Login Page

- src/components/AppShelf/AppShelf.tsx
> ✨ Ability to toggle categories

- src/components/AppShelf/AppShelf.tsx
- src/components/Settings/SettingsMenu.tsx
- src/components/modules/calendar/CalendarModule.tsx
- src/components/modules/downloads/DownloadsModule.tsx
- src/components/modules/downloads/TotalDownloadsModule.tsx
- src/tools/humanFileSize.ts
Feature
Added:
- ETA on Torrents Downloads
- Torrent size on Torrents Downloads
- Paused state on progress bar for Torrents Downloads
Changed:
- Fixed spelling of Customizations
- Fixed build issue from #193 
Paused : 
Downloading :
> More Information in Torrents Module

- src/components/Settings/CommonSettings.tsx
- src/components/WidgetsPositionSwitch/WidgetsPositionSwitch.tsx
- src/components/layout/Aside.tsx
- src/components/layout/Layout.tsx
- src/components/layout/Navbar.tsx
- src/components/layout/Widgets.tsx
- src/tools/types.ts
Feature
A switch to switch widgets bar from right to left
`widgetPosition` in config
> feat: could position widgets at left

- README.md
- data/constants.ts
- package.json
- src/components/AppShelf/AddAppShelfItem.tsx
- src/components/AppShelf/AppShelf.tsx
- src/components/AppShelf/AppShelfItem.tsx
> Revert "v0.7.1"

- src/components/AppShelf/AppShelf.tsx
> 🐛Tiles could be moved accidentally on mobiles

- src/components/modules/calendar/CalendarModule.tsx
- src/components/modules/moduleWrapper.tsx
> ✨ Configure calendar widget to show Sunday first

- src/components/AppShelf/AddAppShelfItem.tsx
Can someone please test this out and tell if it's what they wanted ?
> 🔧 Make credentials non-required for torrents

- src/components/AppShelf/AddAppShelfItem.tsx
- src/components/AppShelf/AppShelfItem.tsx
- src/components/AppShelf/AppShelfMenu.tsx
- src/components/modules/ping/PingModule.story.tsx
- src/components/modules/ping/PingModule.tsx
- src/pages/api/modules/downloads.ts
- src/pages/api/modules/ping.ts
- src/tools/types.ts
Feature 
**Additions**
- New Advanced Options Tab
- New HTTP Status Code Selector
- New Tab or Same Window Selector
- Updated Service Addition UI
**Fixes**
- Transmission/Deluge Password Requirement
#219, #218, #201 
- Status - What HTTP Status codes are "Online" (No Value (Undefined) = 202)
- Target - Open in New Tab or Same Window (No Value (Undefined) = New Tab)
https://user-images.githubusercontent.com/39219859/174163407-dda64412-44bc-4518-836a-9d51fa4fa034.mp4
> ✨Service Addition Overhaul

- src/components/Settings/CommonSettings.tsx
> Feature(?) 
> This PR adds a Discord button in the CommonSettings
> Closes #261 
> ![image](https://user-images.githubusercontent.com/71191962/175018010-0bf1ea8b-cf60-4bae-a197-d702296442cd.png)
> 💬 Adds Discord Button (#261)

- src/components/AppShelf/AddAppShelfItem.tsx
Disables checks for the image URL, fixes #256
> 🐛 Allow anything in the input for the form.

- src/components/AppShelf/AddAppShelfItem.tsx
- src/components/modules/downloads/DownloadsModule.tsx
- src/pages/api/modules/downloads.ts
This PR tries to change the type of iteration from a FOR loop to a MAP, which greatly reduces the complexity of the compiled code.
> :bug: Fix itteration on the different types of services

- docs/modules/built-in-modules/index.md
- docs/modules/built-in-modules/module-weather.md
Documentation
New Blog post for version 0.8.2
> 📝 fix typo in documentation for module overview

- docs/community/donate.md
- docs/community/frequently-asked-questions.md
- docs/community/get-in-touch.md
- docs/community/known-issues.md
Documentation
Added a page for the known issues
> 📄 add known issues page

- docusaurus.config.js
Documentation
We should link our demo in the navbar to make it more visible and easier to find.
This pr adds a demo link to https://homarr.ajnart.fr/
> 📄add demo to navbar

- src/modules/dashdot/DashdotModule.tsx
- src/pages/api/modules/dashdot.ts
> 🔧 Dashdot module changes

- next.config.js
- src/components/AppShelf/AppShelfItem.tsx
- src/pages/api/imageproxy.ts
> ✨ Add caching for icons with an image proxy

- docs/modules/built-in-modules/module-calendar.md
- package.json
- yarn.lock
Documentation
- Upgrade Docusaurus from 2.0.0-beta21 to 2.0.1
- Fix broken links that prevented Vercel from making builds
> 📄 fix broken docusaurus links and upgrade to 2.0.1

- docs/modules/built-in-modules/module-calendar.md
Documentation
- Specify the time range of loaded releases in the calendar module
> 📄 specify loading range for calendar releases

- .editorconfig
> Feature
> Add .editorconfig file in order to override default user's settings according to ESLint config file
> Related issue: #353 
> .editorconfig
> :wrench: Add .editorconfig

- README.md
Documentation
- Remove invalid characters from the quick start docker-compose yml in Readme
> 📄 fix docker-compose in readme

- src/components/AppShelf/AddAppShelfItem.tsx
- src/tools/addToHomarr.ts
> Changes Dashboard icons url to new repo.
> 🚛 Move WalkxHub > WalkxCode

- src/tools/types.ts
Bugfix
Add the status and description to the list
[381](https://github.com/ajnart/homarr/issues/381)
N/A
N/A
> #381 - Add "405 - Method Not Allowed" for statuses

- README.md
Documentation
- Update links for https://github.com/ajnart/homarr-docs/pull/4
> 📝 adjust links for documentation update

- src/modules/dashdot/DashdotModule.tsx
Bugfix
- Fix compact layout #408 
Fixed Issue: #408
> 🐛 fix dash. layout bugs & compact mode

- src/components/layout/Widgets.tsx
- src/modules/calendar/CalendarModule.tsx
- src/modules/dashdot/DashdotModule.tsx
Bugfix
- Add margin for calendar days for better spacing #422 
- Fix layout for calendar header to avoid overflow with menu #422 
- Fix margin for widgets stack that it matches with the calendar #422
> 🐛 fix calendar and aside UI issues

- src/modules/dashdot/DashdotModule.tsx
> Bugfix
>  Do not translate dashdot params
> Related issue: #444
> [Fix for #444] Do not translate params for dashdot

- public/locales/da/settings/customization/page-appearance.json
- public/locales/de/settings/customization/page-appearance.json
- public/locales/en/settings/customization/page-appearance.json
- public/locales/es/settings/customization/page-appearance.json
- public/locales/fr/settings/customization/page-appearance.json
- public/locales/he/settings/customization/page-appearance.json
- public/locales/it/settings/customization/page-appearance.json
- public/locales/ja/settings/customization/page-appearance.json
- public/locales/ko/settings/customization/page-appearance.json
- public/locales/lol/settings/customization/page-appearance.json
- public/locales/nl/settings/customization/page-appearance.json
- public/locales/pl/settings/customization/page-appearance.json
- public/locales/sl/settings/customization/page-appearance.json
- public/locales/sv/settings/customization/page-appearance.json
- public/locales/uk/settings/customization/page-appearance.json
- public/locales/zh/settings/customization/page-appearance.json
- src/components/AppShelf/AddAppShelfItem.tsx
- src/tools/addToHomarr.ts
Bugfix
In version 0.10.3, we introduced new paths for the favicon, but we forgot to change the default path. This PR changes the default path to the correct and new one.
> 🐛Fix default favicon path

- next-i18next.config.js
- src/tools/language.ts
> :globe_with_meridians: Add Vietnamese 🇻🇳 language support

- src/modules/dashdot/DashdotModule.tsx
Bugfix
- Fixed color scheme for iframes of Dash. module
- #503
> 🐛 Iframe color scheme for Dash. module

- src/pages/api/configs/tryPassword.tsx
> #506 Add warning on wrong password attemps

- src/modules/docker/DockerTable.tsx
Bugfix
removes disabled prop to the docker table search input
Related issue: #547
> 🐛 fix docker searchbar

- src/components/Dashboard/Modals/SelectElement/Components/Overview/AvailableElementsOverview.tsx
- src/tools/config/migrateConfig.ts
> 🐛 Fix config migrator wrapper positons

- README.md
- data/constants.ts
- next-i18next.config.js
- src/components/Dashboard/Modals/SelectElement/Components/Overview/AvailableElementsOverview.tsx
- src/tools/config/migrateConfig.ts
> 🚑️ Emergency bugfix for config migrator

- src/components/Dashboard/Tiles/Apps/AppTile.tsx
Bugfix
- Added minimum width to parent element to fix SVG loading, as this seems to be a bug with browers: https://stackoverflow.com/a/29691611
Related issue: #579
> 🐛 #579 fix svg images for app tiles

- src/components/Dashboard/Tiles/Apps/AppTile.tsx
Fixes Hide overflowing app names / option to hide app name #590
> ♻️ Work on app tile design

- src/modules/Docker/ContainerActionBar.tsx
> 🐛 Make PublicPort for Docker containers nullable

- src/components/Dashboard/Modals/EditAppModal/Tabs/IntegrationTab/Components/InputElements/IntegrationSelector.tsx
- src/modules/Docker/ContainerActionBar.tsx
> :bug: Fixing zIndex when using "add to Homarr"

- src/widgets/calendar/CalendarTile.tsx
> 💄 Fix Calendar widget UI

- .eslintrc.js
- public/locales/en/modules/torrents-status.json
- src/hooks/widgets/torrents/useGetTorrentData.tsx
- src/pages/api/modules/torrents.ts
- src/types/api/NormalizedTorrentListResponse.ts
- src/widgets/torrent/TorrentQueueItem.tsx
- src/widgets/torrent/TorrentTile.tsx
- src/widgets/torrentNetworkTraffic/TorrentNetworkTrafficTile.tsx
Feature
- Replaced the tooltip with a popover
- Added details about the torrents
- Changed the API return more granular data for future extension (eg. label filtering)
- Performance and error handling should be slightly improved, as a faulty client will no longer cause the application to crash
#572 
#498 
#515
> ✨ Add detail popover for torrents list and better error handling for torrents

- data/configs/default.json
Bugfix
Fix the default config to contain the correct wrapper positions
> 🔧 Fix wrapper position in default config

- src/components/Dashboard/Views/DashboardView.tsx
- src/components/Dashboard/Wrappers/Sidebar/Sidebar.tsx
- src/components/Dashboard/Wrappers/gridstack/init-gridstack.ts
Margins have been reduced in the sidebars
> 🎨 Tighten up sidebars

- src/tools/config/migrateConfig.ts
Bugfix
- Filter out disabled modules and not convert them to widgets
Related issue: #576
> 🐛 Fix crash with disabled modules in migrator #576

- src/components/Dashboard/Modals/EditAppModal/Tabs/NetworkTab/NetworkTab.tsx
- src/components/Dashboard/Modals/SelectElement/Components/Overview/AvailableElementsOverview.tsx
- src/components/Dashboard/Tiles/Apps/AppPing.tsx
- src/modules/Docker/ContainerActionBar.tsx
- src/tools/config/migrateConfig.ts
- src/types/app.ts
> Revert "🐛 rename okStatus to statusCodes"

- src/modules/Docker/DockerModule.tsx
- src/modules/Docker/DockerTable.tsx
Added a keybind, made the text bigger, offeset the scrollbar, made the table take more space
> 💄 Docker module improvements

- src/components/Dashboard/Wrappers/Category/useCategoryActions.tsx
Bugfix
- Refactored code to remove ESLint warnings
- Set default main wrapper ID to 0
Related issue: #621, #630
> 🐛 Refactor category actions and fix wrong wrapper #630

- src/components/layout/header/Search.tsx
- src/modules/common/MediaDisplay.tsx
Looks a lot better on mobile, fixes #502
> Rework media display for Overseerr

- src/components/layout/header/Header.tsx
Bugfix
- Made the header have the height ``auto``, so it sizes better with wrapped text
- Seems like this doesn't have any bad affect on other components of Homarr. So I wouldn't mind if we merge this.
- #606
> 💄 Fix overflowing text wrap in header for page title #606

- public/locales/en/modules/dashdot.json
- src/widgets/dashDot/DashDotGraph.tsx
- src/widgets/dashDot/DashDotTile.tsx
Feature
- Added a new option
- Added translation for the new option
- Add the new query param
Related issue: #641
> ✨ Add switch for percentages in dash. widget #641

- src/modules/common/MediaDisplay.tsx
- src/widgets/calendar/MediaList.tsx
> 661 add fix for calendar pop up size on mobile

- public/locales/en/modules/calendar.json
- src/modules/common/MediaDisplay.tsx
- src/pages/api/modules/calendar.ts
- src/widgets/calendar/CalendarTile.tsx
> 538-sonarr-v4

- src/components/Dashboard/Tiles/Apps/AppTile.tsx
- src/components/Dashboard/Tiles/HomarrCardWrapper.tsx
- src/components/Dashboard/Wrappers/Category/Category.tsx
- src/components/layout/Layout.tsx
- src/components/layout/Logo.tsx
- src/components/layout/header/Header.tsx
- src/components/layout/header/Search.tsx
Refactoring only
- Added static class names for easier customization
Requested by @blassley
> ♻️ Add static CSS class names

- src/components/Dashboard/Views/useEditModeStore.ts
- src/components/Dashboard/Wrappers/gridstack/store.tsx
- src/config/store.ts
- src/pages/404.tsx
- src/tools/client/zustands/usePackageAttributesStore.ts
> Fix Zustand imports

- public/locales/en/layout/modals/about.json
- src/components/Dashboard/Modals/AboutModal/AboutModal.tsx
- src/components/layout/header/Header.tsx
- src/components/layout/header/SettingsMenu.tsx
- src/hooks/useEditModeInformation.ts
- src/pages/_app.tsx
- src/pages/api/configs/[slug].ts
Feature
- Add experimental environment variable to disable edit mode
- Hide buttons and settings when edit mode is disabled
- Pass the server side state of the env to the client
> ✨ Add disable edit mode environment variable

- src/components/Dashboard/Wrappers/WrapperContent.tsx
- src/widgets/WidgetWrapper.tsx
- src/widgets/calendar/CalendarTile.tsx
- src/widgets/dashDot/DashDotTile.tsx
Bugfix
Added a hook that updates properties to defaultValue, if they don't exist
Could also be extended to delete old no longer used keys.
> Fix Error with latest Dashdot changes

- package.json
- src/middleware.ts
- yarn.lock
Bugfix
- Bump NextsJS
- Remove unused variable
#716
> 🚑 Fix URL malformed

- .github/workflows/docker_dev.yml
- .gitignore
- package.json
- turbo.json
- yarn.lock
This commit adds turbo cache usage
> Turbo cache

- public/locales/en/widgets/error-boundary.json
- src/tools/server/translation-namespaces.ts
- src/widgets/WidgetWrapper.tsx
- src/widgets/boundary.tsx
Feature
- Add boundary for client side errors in widgets
> ✨ Add widget error boundary

- src/pages/_app.tsx
Feature
- Add new env variable
- Override default color scheme
#237 
``DEFAULT_COLOR_SCHEME`` = ``[dark, light]``
> ✨ Environment variable for default color scheme #237

- src/pages/api/modules/rss/index.ts
- src/widgets/rss/RssWidgetTile.tsx
Bugfix
- Add conditional rendering for link
Fixes #741
> 🚑 Fix RSS widget crash

- public/locales/en/layout/modals/about.json
- src/components/Dashboard/Modals/AboutModal/AboutModal.tsx
- src/components/layout/header/Actions/ToggleEditMode/ToggleEditMode.tsx
> ✨ Add a simple keybind viewer in about menu #751

- src/pages/api/modules/media-server/index.ts
- src/types/api/media-server/session-info.ts
- src/widgets/media-server/MediaServerTile.tsx
- src/widgets/media-server/NowPlayingDisplay.tsx
> ✨ Add TV show name in media info and style changes

- .gitignore
- src/pages/api/docker/DockerSingleton.ts
**DOCKER_HOST** host for docker with url
**DOCKER_PORT** port for docker with url
> ✨ Add support for proxied docker #758

- src/hooks/useScreenLargerThan.ts
Bugfix
- Fixes the breakpoint where mobile ribbons would not toggle
> 🚑 Fix sidebar ribbons breakpoint

- data/configs/default.json
- src/components/Settings/Customization/Meta/BackgroundChanger.tsx
- src/components/Settings/Customization/Meta/FaviconChanger.tsx
- src/components/layout/header/Meta/Head.tsx
Bugfix
- Fix default paths
- Fix placeholders
Fixes #763 and #801
> ♻️ Fix default img paths

- src/tools/server/sdk/plex/plexClient.test.ts
- src/tools/server/sdk/plex/plexClient.ts
- src/types/api/media-server/session-info.ts
Bugfix
- Allow anonymous users
- Make ``<Session/>`` optional
#739
> 🐛 Anonymous Plex user

- src/components/Dashboard/Tiles/Widgets/WidgetsEditModal.tsx
- src/widgets/rss/RssWidgetTile.tsx
> 🐛 Fix RSS client bug

- public/locales/da/modules/media-requests-list.json
- public/locales/de/modules/media-requests-list.json
- public/locales/en/modules/media-requests-list.json
- public/locales/es/modules/media-requests-list.json
- public/locales/he/modules/media-requests-list.json
- public/locales/it/modules/media-requests-list.json
- public/locales/no/modules/media-requests-list.json
- public/locales/sk/modules/media-requests-list.json
> ✏️ Fix typo in media request widget

- package.json
> 🔖 Update version in package.json

- next-i18next.config.js
> Bugfix
> The wrong locale code has been used for turkish translation
> Related issue: #877
> 🐛 Fix wrong i18n locale for turkish

- public/locales/en/modules/bookmark.json
- src/widgets/bookmark/BookmarkWidgetTile.tsx
> Feature 
> Adds an option to open the links in the bookmarks widget in a new tab 
> Related issue: #977 
>
> ✨ Bookmarks - Open in new Tab

- Dockerfile
Implements the fix from https://github.com/vercel/next.js/issues/44384
> 🐛 Enotfound Error

- yarn.lock
Fix build errors due to issues with the lock file
> 📌 Update lockfile

- src/modules/Docker/DockerModule.tsx
Simple fix. 
Fixes #1064 #1077
> 🐛 Try fixing docker menu button

- public/locales/en/modules/calendar.json
- src/widgets/calendar/CalendarDay.tsx
- src/widgets/calendar/CalendarTile.tsx
Added selected day highlight
Fixes #1145
Added font size setting
General rework of the calendar visuals
> ✨ Add day select highlight and font resize to Calendar

- src/pages/api/modules/dns-hole/control.ts
- src/pages/api/modules/dns-hole/summary.spec.ts
- src/pages/api/modules/dns-hole/summary.ts
- src/server/api/routers/dns-hole.ts
- src/tools/config/getFrontendConfig.ts
- src/types/app.ts
> Bug fix
> I have changed the intergration field from password to apiKey
> Related issue: #1126
> ![image](https://github.com/ajnart/homarr/assets/40298510/b0eb62f0-b74d-4049-857a-3f213b9a15a0)
> ✏️  fix pi-hole integration field from password to apiKey

- src/components/Settings/SettingsDrawer.tsx
I'm trying to fix the issue with the settings drawer
> 🐛 Fix issue with drawer transition

- data/configs/default.json
> ✅ Remove version name in default config

- src/widgets/calendar/CalendarDay.tsx
> One of: Bugfix / cosmetic
> There was a slight mistake on one line that rendered the highlight function useless. Just fixing that and a very slight rework for alinement.
> 🐛 hotfix calendar highlight bug

- src/pages/api/modules/dns-hole/control.ts
- src/pages/api/modules/dns-hole/summary.ts
- src/server/api/routers/dns-hole.ts
- src/widgets/dnshole/DnsHoleControls.tsx
> Bugfix
> Fix issue that controls of dns-hole did the reversed action (enable / disable)
> Related issue: #1141
> 🐛 Fix reversed dns-hole controls

- public/locales/en/layout/common.json
> 🌐 Restore translations for common layout

- src/widgets/media-requests/MediaRequestListTile.tsx
> 🐛 Fix Overseerr media request overflow

- src/components/IconSelector/IconSelector.tsx
> 🐛 Fix clear icon in apperance tab

- src/components/Dashboard/Tiles/Widgets/Inputs/LocationSelection.tsx
> ✨ Improvements to city selection in weather widget

- src/components/Dashboard/Tiles/Apps/AppPing.tsx
- src/server/api/routers/app.ts
> Bugfix
> Remove config read from cookies
> Related issue: #1176
> 🐛 Fix ping not reading from correct config

- src/components/Dashboard/Mobile/Ribbon/MobileRibbonSidebarDrawer.tsx
> Bugfix
> Fix issue that drawer for sidebar does not work.
> Related issue: #1193
> 🐛 Fix sidebar drawer not working

- package.json
- src/config/provider.tsx
- src/pages/_app.tsx
> Fixed that on intial load the color scheme, and the initial config are defined
> Related issue: #1220
> 🐛 Fix config appearance on initial load

- public/locales/en/layout/modals/add-app.json
- src/components/Dashboard/Modals/EditAppModal/EditAppModal.tsx
- src/components/Dashboard/Modals/EditAppModal/Tabs/AppereanceTab/AppereanceTab.tsx
- src/components/Dashboard/Modals/EditAppModal/Tabs/BehaviourTab/BehaviourTab.tsx
- src/components/Dashboard/Modals/EditAppModal/Tabs/GeneralTab/GeneralTab.tsx
- src/components/Dashboard/Modals/EditAppModal/Tabs/NetworkTab/NetworkTab.tsx
- src/components/Dashboard/Modals/SelectElement/Components/Overview/AvailableElementsOverview.tsx
- src/components/Dashboard/Tiles/Apps/AppTile.tsx
- src/modules/Docker/ContainerActionBar.tsx
- src/types/app.ts
> Feature / Cosmetic
> Because of file and commits conflict, it was decided it the better to redo the PR
> Please refer to PR #1218 
> fixes #549 and fixes #834 
> Refer to PR #1218
> ✨App tile UI change

- src/components/Dashboard/Tiles/Apps/AppTile.tsx
> 💄 Improve sizing of app name

- public/locales/en/modules/weather.json
- src/widgets/weather/WeatherIcon.tsx
- src/widgets/weather/WeatherTile.tsx
> Feature
Fixes #1182 
> Adds an option to be able to show the city on weather tile.
> Related issue: #1182
> ✨ display location name on a weather tile

- src/widgets/torrent/TorrentQueueItem.tsx
- src/widgets/torrent/TorrentTile.tsx
> Bugfix
> Just added transparency to table and info
> Related issue: #1251
> 🐛 App Transparency not used by torrent tile table

- src/server/api/routers/media-request.ts
> Bugfix
> Fixed issue with wrong link for tv requests
> Related issue: #1259
> 🐛 Issue with media request url

- src/components/Dashboard/Tiles/Apps/AppPing.tsx
- src/server/api/routers/app.ts
- src/utils/api.ts
https://saturncloud.io/blog/what-is-the-maximum-length-of-a-url-in-different-browsers/
- Fix the max URL length in tRPC 
- Fix issues with cached pings (will now fetch at every page reload (but I'd like the ping button to be click-able to restart the ping in the future))
-
> Fix issues with URL being too long when pinging many apps

- package.json
- src/components/Dashboard/Tiles/Apps/AppTile.tsx
Just merged with master and increased version to 0.13.2
> 🔖 Increase version to 0.13.2

- data/configs/default.json
- src/components/Dashboard/Tiles/Apps/AppTile.tsx
> v0.13.2 - Hotfixed

- src/server/api/routers/rss.ts
- src/widgets/rss/RssWidgetTile.tsx
> Bugfix
> RSS feed was stuck on loading when there was no feed when it should have shown the text shown in the following screenshot.
> ![image](https://github.com/ajnart/homarr/assets/26098587/969371eb-170c-4572-9019-f8e752e958ea)
> 🐛 RSS empty feed stuck on loading

- public/locales/en/layout/modals/add-app.json
- src/components/Dashboard/Modals/EditAppModal/Tabs/AppereanceTab/AppereanceTab.tsx
- src/components/Dashboard/Modals/SelectElement/Components/Overview/AvailableElementsOverview.tsx
- src/components/Dashboard/Tiles/Apps/AppTile.tsx
- src/modules/Docker/ContainerActionBar.tsx
- src/tools/config/getFrontendConfig.ts
- src/types/app.ts
> Cosmetic / Feature
> Add the ability to change the font size for the app name when shown on the tile
> Closes #1326 
> ![image](https://github.com/ajnart/homarr/assets/26098587/ee0d85f0-b081-4837-96fb-c21584d003df)
> 💄 Add custom font sizing for app name

- src/tools/server/sdk/pihole/piHole.spec.ts
- src/tools/server/sdk/pihole/piHole.ts
> Test files
> Update vitest test for Pihole as sdk changed
> enable -> change not done -> throw error
> disable -> change not done -> throw error
> enable -> cycle 10 times -> expected value
> disable -> cycle 10 times -> expected value
> on all, added mockup for getSummary as it is now called too
> ✅ Update vitest test for Pihole as sdk changed

- src/tools/_tests/bytesHelper.spec.ts
- src/tools/_tests/humanFileSize.spec.ts
- src/tools/_tests/language.spec.ts
- src/tools/humanFileSize.ts
- src/tools/language.ts
Just added a few tests because I was in the mood of it
> ✅ Add tests for some tools functions

- package.json
- yarn.lock
> Bugfix
> Same dependency fix we had to do on dev.
> ⬇️ next js 13.4.19 to 13.4.12

- src/env.js
> Bugfix
> Port reported NaN instead of actual port.
> Multiple feedbacks on discord
> 🐛 env.port reporting NaN bug fix

- src/widgets/media-server/DetailCollapseable.tsx
- src/widgets/media-server/TableRow.tsx
> Cosmetic
> Change modal of media-server to popover to improve modals consistency.
> Target: all modals on tap/click in a popover, for Media-server, Calendar and torrent download
> Related issue: #1348
> ![image](https://github.com/ajnart/homarr/assets/26098587/dddd38e2-08e8-40d6-93bf-5fdfefda048e)
> 💄 Change modal for media-server

- src/widgets/video/VideoStreamTile.tsx
> Bugfix
> Title
> Discord report
> 💄Allow user to make video stream smaller than 3*2

- src/components/Manage/User/Invite/delete-invite.modal.tsx
- src/server/api/root.ts
- src/server/api/routers/invite/invite-router.spec.ts
- src/server/api/routers/invite/invite-router.ts
- src/server/db/index.ts
*Thank you for contributing to Homarr! So that your Pull Request can be handled effectively, please populate the following fields*
> Tests
> Added two tests for invite router
> Related issue: #1332
> ✅ Add tests for invite router

- src/components/Manage/Tools/Docker/docker-select-board.modal.tsx
> 🐛 Fix the leading slash when adding container via docker

- src/pages/_app.tsx
Readded missing package attribute setter in _app.tsx
> 🐛 About version and dependencies not present

- public/locales/en/modules/calendar.json
- src/modules/common/MediaDisplay.tsx
- src/widgets/calendar/CalendarTile.tsx
> Feature
> Radarr's v5 did the same change as sonarr's regarding the posters, so this adds the same toggle in the calendar's options.
> ✨ Adds support for poster on Radarr v5's api

- src/server/api/routers/weather.ts
- src/widgets/weather/WeatherTile.tsx
This allows for request caching on the disk using node's fetch
> ✨ Fetch the weather using a local request instead of a server-side one

- README.md
Related to https://github.com/ajnart/homarr-docs/pull/83/commits/61ce88b5b7c39f31e4c77eee14192e799f2307d3
> Fix crowdin links

- src/server/api/routers/weather.ts
- src/widgets/weather/WeatherTile.tsx
> Revert "✨ Fetch the weather using a local request instead of a server-side one"

- next-i18next.config.js
- src/tools/language.ts
Closes #https://github.com/ajnart/homarr/issues/1515
> Add Chinese traditional as `tw`

- src/components/layout/Meta/CommonHead.tsx
> Update CommonHead.tsx with `crossorigin="use-credentials"`

- public/locales/en/modules/dns-hole-summary.json
- public/locales/en/settings/customization/general.json
- public/locales/sv/settings/customization/general.json
> Fixed Typos

- public/locales/en/modules/calendar.json
- src/modules/common/MediaDisplay.tsx
- src/server/api/routers/calendar.ts
- src/widgets/calendar/CalendarTile.tsx
> Feature
> Handles sonarr v4 and radarr v5 automatically, removing the need for the user inputs.
> ✨ Auto handle sonarr and radarr API differences

- src/styles/global.scss
> ✨ Add scrollbar-gutter property to global styles

- scripts/run.sh
> Bugfix
> Add rm command before each mv command in run.sh script
> [Post in Discord](https://discord.com/channels/972958686051962910/1172853125879709696)
> 🐛 Fix podman issue

- src/server/api/routers/docker/router.ts
Fixes Lost docker connection via TCP with 0.14.0 update #1577
> 🐳 Fix docker TCP not working

- public/locales/en/settings/customization/page-appearance.json
> Bugfix ?
> The image is not repeated any may not fill the entire space (recommended)
> =>
> The image is not repeated and may not fill the entire space (recommended)
> Fixed typo in public/locales/en/settings/customization/page-appearance.json

- package.json
Just a simple version bump for the release
> 🔖 Bumb version to 0.14.1

- Dockerfile
> 🐛 File busy with node > 20.3

- src/components/layout/Templates/BoardLayout.tsx
> Bugfix
> Change link to current documentation link
> Related issue: #1646
> 🐛 Link to definition of screen sized for edit mode notification wrong

- public/site.webmanifest
> Feature
> Add `name` and `start_url` property to `site.webmanifest`
> Related issue: #1674
> ✨ Add support for installation in address bar

- src/components/layout/header/AvatarMenu.tsx
> Feature
> Use Gravatar as image source when available, fallback on the 2 letter from username
> Issue raised on discord
> ![image](https://github.com/ajnart/homarr/assets/26098587/99078a3c-2070-4c79-b8b8-38e775f70519)
> ✨ Use gravatar with user email

- src/components/layout/Templates/ManageLayout.tsx
Made by: Thomas Camlong <ajnart@users.noreply.github.com>
> Refactoring Only
> Slight code improvement by ajnart when looking at other things
> ⚡️ Improve code in manage layout page

- src/components/Manage/User/Edit/GeneralForm.tsx
- src/components/Manage/User/Edit/ManageUserDanger.tsx
- src/components/Manage/User/Edit/ManageUserSecurityForm.tsx
- src/pages/manage/users/index.tsx
> Review
> Implement the comments I made in my review of the PR
> Done:
> - Table behavior in mobile mode
> - Email edit validation
> - User deletion redirect to manage user page on success
> - Password saving unticks the confirm checkbox
> - Username/E-Mail save button added "type=submit" and "form.resetDirty()" on settle
> - Formatted and organize import on changed files.
> Not addressed:
> - Allow normal users to edit themselves.
> - Avatar is default in all cases.
> ![image](https://github.com/ajnart/homarr/assets/26098587/0e867898-82d1-4466-9d87-654367e00e0c)
> Address own review comments on PR #1748

- README.md
Documentation
Updated installation instruction links from https://homarr.dev/docs/introduction/installation to https://homarr.dev/docs/getting-started/installation/
N/A
N/A
N/A
> Updated dead installation links in README.md

- src/widgets/torrent/TorrentTile.tsx
> refactor: improve torrent table design

- public/locales/en/modules/smart-home/entity-state.json
- public/locales/en/modules/smart-home/trigger-automation.json
- src/server/api/routers/smart-home/entity-state.ts
- src/tools/server/sdk/homeassistant/HomeAssistant.ts
- src/tools/server/translation-namespaces.ts
- src/widgets/index.ts
- src/widgets/smart-home/entity-state/entity-state.widget.tsx
- src/widgets/smart-home/trigger-automation/trigger-automation.widget.tsx
> feature: trigger automations

- Dockerfile
> fix: database is not initialized inside the docker container

- public/locales/en/modules/rss.json
- src/server/api/routers/rss.ts
- src/widgets/rss/RssWidgetTile.tsx
- Add support for Youtube feed #1808 
- Add ascending sorting to RSS items #1809 
https://noted.lol/rss/
https://www.youtube.com/feeds/videos.xml?channel_id=UCfE5Cz44GlZVyoaYTHJbuZw
> feature: rss improvements

- public/locales/en/common.json
- src/components/Dashboard/Modals/EditAppModal/EditAppModal.tsx
- src/components/Dashboard/Modals/SelectElement/Components/Overview/AvailableElementsOverview.tsx
- src/components/Dashboard/Tiles/Apps/AppMenu.tsx
- src/components/Dashboard/Tiles/GenericTileMenu.tsx
- src/tools/config/wrapper-finder.ts
Will **not copy** the size and position.
> feat: #1835 copy apps

- src/pages/_app.tsx
- src/tools/language.ts
> fix: #1859 dayjs locale translation

- src/components/Manage/Board/create-board.modal.tsx
- src/server/api/routers/config.ts
> Add check for already existing name upon creating board.
> Closes issue: #1886
> 🐛 Board create name bug fix

- src/widgets/bookmark/BookmarkWidgetTile.tsx
> Remove url length checks in Bookmarks

- src/widgets/indexer-manager/IndexerManagerTile.tsx
> Set maximum size for indexer manager to 12

- next-i18next.config.js
- src/tools/language.ts
> add Lithuanian support

- next-i18next.config.js
- src/tools/language.ts
> Add Estonian language

- src/components/layout/Templates/BoardLayout.tsx
- src/components/layout/Templates/ManageLayout.tsx
Found two links that are death and made them work again
> Fix death app links

- src/server/api/routers/openmediavault.ts
> Build related changes
> Issue - #1962
> OMV 7 support

- public/locales/en/modules/health-monitoring.json
- src/server/api/routers/openmediavault.ts
- src/widgets/health-monitoring/HealthMonitoringCpu.tsx
- src/widgets/health-monitoring/HealthMonitoringFileSystem.tsx
- src/widgets/health-monitoring/HealthMonitoringMemory.tsx
- src/widgets/health-monitoring/HealthMonitoringTile.tsx
> Bugfix
> fix cpu temp when not available, fix hover dropdown, resize progress rings, fix data update interval.
> Related issue: #1962
> Health monitoring hotfix

- src/widgets/weather/WeatherTile.tsx
> Bugfix
> add refresh interval
> Related issue: #1825
> Weather widget does not refresh automatically

- src/components/Dashboard/Modals/EditAppModal/Tabs/AppereanceTab/AppereanceTab.tsx
> fix: #1976 lower debounce time

- public/locales/en/modules/torrents-status.json
- src/widgets/torrent/TorrentTile.spec.ts
- src/widgets/torrent/TorrentTile.tsx
> Feature
> Add option to customize torrent widget columns
> Fix 100.0% to 100%
> Related issue: #1471 
> Related issue: #1832 
> Related issue: #1354 
> Related issue: #1929
>
> Columns customize

- src/tools/language.ts
> feat: add romanian language support

- src/components/Dashboard/Tiles/Widgets/Inputs/LocationSelection.tsx
- src/components/Dashboard/Tiles/Widgets/WidgetsMenu.tsx
- src/components/Dashboard/Wrappers/Category/Category.tsx
- src/components/Manage/Board/create-board.modal.tsx
- src/components/Manage/Board/delete-board.modal.tsx
- src/components/Manage/Tools/Docker/docker-select-board.modal.tsx
- src/components/Manage/User/Invite/copy-invite.modal.tsx
- src/components/Manage/User/Invite/create-invite.modal.tsx
- src/components/Manage/User/change-user-role.modal.tsx
- src/components/Manage/User/delete-user.modal.tsx
- src/components/layout/header/AvatarMenu.tsx
- src/styles/global.scss
> Bugfix 
> Fix browser console error about nested headers upon opening a modal.
> Fix browser console error about nested buttons when entering edit mode.
> Fix browser console error about nested buttons upon opening the Avatar Menu.
> fix: Modals titles nested headers and edit mode nested buttons errors

- package.json
> Version change
> Increased version to 0.15.3, this should be used to create a new release once the related pull requests are merged
> Related issue: #2002 #1984
> core: increase version to 0.15.3

- next-i18next.config.js
- src/tools/language.ts
> Add New Language Arabic

- public/locales/en/modules/indexer-manager.json
- src/widgets/indexer-manager/IndexerManagerTile.tsx
> Feature
> Add indexers site hyperlink
> Requested via Discord
> feat: add indexers site hyperlink

- src/components/Dashboard/Tiles/Apps/AppPing.tsx
Bugfix
Added missing refetch properties
> Related issue: #1707
> fix: #1707 refech interval app pings

- README.md
> Documentation
> Fixed two links in README.md
> No related issues
> None
> Not necessary
> docs: Fixed links in README.md

- Dockerfile
- docker/entrypoint/docker-entrypoint.d/00-user-setup.sh
This solves all issues regarding docker that I found:
- Docker socket volumne not working when executing user is root
- Wrong default database url in Dockerfile
- Data directory not writable for running user
> fix: dev docker issues

- .vscode/settings.json
- package.json
- src/server/api/routers/board.ts
- src/server/api/routers/media-request.ts
- src/validations/boards.ts
- src/widgets/dnshole/TimerModal.tsx
- src/widgets/iframe/IFrameTile.tsx
- src/widgets/media-requests/MediaRequestListTile.tsx
- src/widgets/media-requests/MediaRequestStatsTile.tsx
- src/widgets/media-requests/media-request-types.tsx
> Release 0.15.8

- .vscode/settings.json
- drizzle/0001_brave_mimic.sql
- drizzle/meta/0001_snapshot.json
- drizzle/meta/_journal.json
- package.json
- public/locales/en/layout/manage.json
- public/locales/en/manage/migrate.json
- src/components/layout/Templates/ManageLayout.tsx
- src/hooks/useSetSafeInterval.tsx
- src/pages/api/migrate.ts
- src/pages/manage/tools/migrate.tsx
- src/server/api/root.ts
- src/server/api/routers/migrate.ts
- src/server/api/routers/notebook.ts
- src/server/db/schema.ts
- yarn.lock
> feat: add 1.0 migration page

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/idea.yml
- .github/ISSUE_TEMPLATE/module.yml
> chore(issue-template): add warning alert to issue templates for 1.0

- src/tools/server/sdk/pihole/piHole.ts
> One of: Bugfix 
Update PiHole authentication. 
See PiHole Docs -> https://docs.pi-hole.net/api/auth/#__tabbed_1_1
> Update PiHole authentication. (PiHole v6)

- src/tools/server/sdk/pihole/piHole.ts
> Revert "Update PiHole authentication. (PiHole v6)"
