ajnart/homarr

Dockerfile
Changed Nginx to use Alpine instead of Debian
Image size is 93 MB smaller and build times are shorter is 36-49s now is 23-36s.
Have been running the latest version built on nginx:alpine on my raspi for the day and nothing seems to be broken. Only add services with no API, so that's the only thing I haven't tested as I don't have one
Will be making alpine builds in my fork till this has been tested more and merged.
```
ghcr.io/c00ldude1oo/mhp           test             ec30655a4d49   35 minutes ago      19.7MB
ghcr.io/ajnart/mhp                latest           afa7d0ba6d4d   10 hours ago        113MB
```
=> Change nginx base to alpine

src/pages/api/modules/downloads.ts
Using origin omit basic authentication that be used for public facing torrents client.
Fix for my messed up PR request #172 
Feature
Allow basic authentication for Deluge and qbittorrent since origin omit basic auth.
The current version use the origin of the URL, this is an issue for users running a Deluge or qbittorent webUI with extra basic authentication.
```
URL {
href: 'https://deluge:REDACTED@deluge.REDACTED.xyz/',
origin: 'https://deluge.REDACTED.xyz',
protocol: 'https:',
username: 'deluge',
password: 'REDACTED',
host: 'deluge.REDACTED.xyz',
hostname: 'deluge.REDACTED.xyz',
port: '',
pathname: '/',
search: '',
searchParams: URLSearchParams {},
hash: ''
}
```
=> Changing deluge/qbittorent to use href instead of origin

src/components/modules/calendar/CalendarModule.tsx
Due to how Sonarr gives dates, they recommend using UTC time when displaying it as it matches their calendar. Took some digging but it fixed it.
> One of: Bugfix 
> Changed Sonarr's API call to use UTC time, that way time's on the calendar are correct.
> Related issue: #187
=> Fix Sonarr Incorrect Dates

src/components/modules/calendar/CalendarModule.tsx
Feature
Indicate current day in calendar.
Firstly I've put primary color to background-color on current day, put it's really too flashy.
- [ x] All changes are backwards compatible
- [ x] There are no (new) build warnings or errors
=> feat: calendar indication about date and w-e with secondary color

src/components/modules/calendar/CalendarModule.tsx
Bugfix 
Fix current day in calendar for light theme, sorry missed to test on it... I'll be blind but it's working.
=> fix: calendar current day for light theme

src/components/modules/downloads/DownloadsModule.tsx
Bugfix
When torrents are not seeding and completed, they report as both progress === 1 and state === 'paused', the old logic checked if it was paused before it checked if it was completed. Now it checks if its completed before it checks if its paused.
Before:
After:
=> 🐛Fix completed torrents progress color

src/components/AppShelf/AppShelfItem.tsx
=> 🐛 Cannot open "New Tab URL" on mobile

src/components/modules/calendar/CalendarModule.tsx
Fix no content showing when 1 of the same service is down.
Bugfix
If you have multiple of the same Arr services, (Ex. 2 Sonarrs), and 1 of the 2 fail, then the calendar fails to display any media.
This was due to it not having a catch statement for when data acquisition would fail and cause an error.
=> 🐛 Fix Calendar not loading content when a service fails

src/components/modules/calendar/CalendarModule.tsx
Bugfix
- https://github.com/ajnart/homarr/commit/6fd23cf6a003a2e666cea30dfb9e031e6e0e6e12 changed how items for the calendar are acquired, making it so every series gets updated when a new one gets added, or one gets moved. This causes the entries in the calendar to duplicate due to old code being left in. The way before this feature change was to grab the old calendar items, and add new items on top of that.
- The sections of code I added made it so instead of the array of calendar entries starting with the old entries, it starts empty, this way duplicates do not occur.
**I have not been able to replicate any bugs …
=> 🐛 Fix Calendar Item Duplication

src/pages/api/modules/calendar.ts
Bugfix
For some reason if the URL ends with /, its breaks Radarr's API, this just removes the slash if it exists.
The reason its an if is because if you do /radarr at the end of your URL, the / isn't added at the end, but if you don't have a / its added.
=> 🐛Fix URL for Radarr and other services

src/components/AppShelf/AddAppShelfItem.tsx, src/pages/api/modules/downloads.ts
Bugfix
This allows you to have more than 1 of the same type of download client.
The code is somewhat similar to #176's fix but using a modern for loop, I couldn't use a forEach() or a map() as the async wouldn't allow proper pushing to the torrents array. And because I could use React's useState I used a regular for loop.
**Edit: Also fixed Torrent's credential requirements for deluge and transmission**
#241
=> 🐛Allow multiple of the same torrent client +1

README.md
Correct the link to Wiki/Integrations
Documentation 
> Update README.md Wiki/Integrations link
=> Update README.md with correct link for Wiki/Integrations

src/components/Settings/CommonSettings.tsx, src/components/modules/search/SearchModule.tsx
> Feature
> This PR adds support for a query placeholder *(%s can be used as a placeholder for the query (e.g. https://search.com?q=%s&lang=en))*, and adds autoFocus to the search bar on page load
> Resolves #267 
> Resolves #268
=> ✨ Adds query placeholder and autoFocus (#267 #268)

src/components/AppShelf/AppShelf.tsx
> Styling
> This changes the styling of the categories to make them more visible when having a custom background, and also fixes open/closing animation smoothness.
> Related 'issue': https://canary.discord.com/channels/972958686051962910/972958689155764326/988616402527219742
https://user-images.githubusercontent.com/71191962/174880300-4ef5bc11-f7aa-4c92-bc12-c06743ecdbff.mp4
=> 💄 Changes AppShelf category styling

src/components/modules/date/DateModule.tsx, src/components/modules/moduleWrapper.tsx, src/components/modules/modules.tsx, src/components/modules/weather/WeatherModule.tsx
This feature allows a module maker to use a list of the different possible values for a module integration.
Fixes #279
=> :sparkles: Add support for lists in module option

docs/modules/built-in-modules/module-weather.md
Documentation
The documentation of the weather module had wrong information about the name you need to specify.
- adjust description for the setting for the weather module
- add guide on how to troubleshoot the weather module
=> 📝 specify open-meteo name parameter

src/components/AppShelf/AddAppShelfItem.tsx
Fix default port for when adding Readarr, currently `8686` but should be `8787` I'm not sure if this change I've made is entirely sufficient for the fix?
See [https://wiki.servarr.com/readarr](https://wiki.servarr.com/readarr).
=> Fix Readarr default port number

src/tools/types.ts
> One of: Feature
> Add a number of high usage docker images to match the type of service to
> N/A
> N/A
> N/A
=> Adding docker images to match

README.md
Documentation (README)
The current url is sending to `advanced-features/integrations` and return 404. 
I think it should be `advanced-configuration/integrations`, as far as I have seen
=> Fix integrations url on README

public/locales/de/settings/customization/page-appearance.json, public/locales/en/settings/customization/page-appearance.json, src/components/Settings/AdvancedSettings.tsx, src/components/layout/Layout.tsx, src/tools/types.ts
> Feature
> Adds a textarea for sutom css to the Customize Settings Tab. The css is loaded in a <style> below <main>
> Related issue: #339
> ![Customize Settings](https://user-images.githubusercontent.com/46794825/186278387-96fbc4ea-0265-4e36-a5f8-0c9db9a67f49.png)
=> :sparkles: Add option for custom CSS to Customization Settings

README.md
> Documentation
> Fixed a typo in the README.md file
=> :pencil2: Fix typo in README.md

src/components/AppShelf/AddAppShelfItem.tsx, src/components/AppShelf/apiKeyPaths.json
>Bugfix
Created a JSON file to add the API Key path for each service instead of using /settings/general for the "Get your API key here" tip (Mainly because Overseerr and Jellyseerr use `/settings` instead of `/settings/general`)
> Related issue: #446 
> `components/AppShelf/apiKeyPaths.json`: Stores the path used for each service
=> :adhesive_bandage: Fix *seerr API key link (#446)

public/locales/en/layout/app-shelf.json, src/components/AppShelf/AppShelf.tsx, src/modules/ModuleTypes.d.ts, src/modules/moduleWrapper.tsx, src/modules/torrents/TorrentsModule.tsx
Bugfix
- Added padding options for customization per module
- Set ``Paper``'s position to relative for correct position of ``<Menu/>``
- Add type definition for ``ModuleMenu`` component
- #411
=> 🐛 Wrong absolute position of torrent options menu

public/locales/en/settings/general/search-engine.json, src/components/SearchNewTabSwitch/SearchNewTabSwitch.tsx, src/components/Settings/CommonSettings.tsx, src/modules/search/SearchModule.tsx, src/tools/types.ts
Change the Search module to open results in the same tab.
When using homarr as the default page for a new tab it makes more sense to open search results in the same tab rather than another new tab.
Also added a toggle if someone prefers it to still be in a new tab.
> One of: Bugfix / Feature
Search module opens results in same tab instead of new tab by default (has toggle)
Added a new variable in the Settings interface to track the toggle switch state.
Added new json files for the toggle text for translations.
=> Change window.open to same tabe instead of new tab

data/constants.ts, package.json, src/modules/dashdot/DashdotModule.tsx
Styling
As we talked about on discord, I made the labels appear only when hovering the specific graph
=> Make Dash. labels only appear on hover

Dockerfile
to ghcr.io/linuxserver/baseimage-alpine:3.17
fixes #240
=> Trying to change back Docker image

README.md
> Documentation
> Updated documentation links
> Removed duplicate/outdated info
> Made the "Read the docs" link more prominent
=> 📝 Link to the docs instead of showing outdated/duplicate info

src/components/Dashboard/Modals/EditAppModal/Tabs/NetworkTab/NetworkTab.tsx, src/components/Dashboard/Modals/SelectElement/Components/Overview/AvailableElementsOverview.tsx, src/components/Dashboard/Tiles/Apps/AppPing.tsx, src/modules/Docker/ContainerActionBar.tsx, src/tools/config/migrateConfig.ts, src/types/app.ts
Thanks to #596 and @jonjon1123 , we can fix the incoherences between `okStatus` and `statusCodes`
=> 🐛 rename okStatus to statusCodes

src/components/Dashboard/Wrappers/Category/Category.tsx, src/components/Dashboard/Wrappers/Category/CategoryEditMenu.tsx
Fixes #636
- Categories are all expanded by default. They can't be collapsed in edit mode to prevent people from collapsing them and then putting apps after then, pushing away apps when it expands and breaking the order of apps
- Category expansion is config-based in local storage
- Compatible with transparent configs
=> Add category collapse

src/pages/api/modules/usenet/history.ts, src/pages/api/modules/usenet/index.ts, src/pages/api/modules/usenet/pause.ts, src/pages/api/modules/usenet/queue.ts, src/pages/api/modules/usenet/resume.ts
For internal ip/urls if the application exists on port 80 or 443. `new Url` will not set port. So this will add defaults based on protocol for http or https.
> Related issue: https://github.com/ajnart/homarr/issues/642
n/a
n/a
=> feat: add support for default ports on http(s) protocols

src/components/Dashboard/Modals/EditAppModal/Tabs/AppereanceTab/AppereanceTab.tsx, src/pages/api/getLocalImages.ts
Fixes #619
We need to decide if this is ok or if we should make it so the icon picker is part of the actual search bar. That would also allow to size icons a little bit bigger because the popover would have the width of the whole input. 
- Maybe we need to mention this somewhere. Perhaps a `TIP` under the input would be a good idea.
=> Add autocomplete to the icon selection screen

src/components/Dashboard/Modals/EditAppModal/Tabs/NetworkTab/NetworkTab.tsx, src/components/Dashboard/Modals/SelectElement/Components/Overview/AvailableElementsOverview.tsx, src/components/Dashboard/Tiles/Apps/AppPing.tsx, src/modules/Docker/ContainerActionBar.tsx, src/tools/config/migrateConfig.ts, src/types/app.ts
Fixes #726
Issue was just a type miscommunication, we renamed 'okStatus' to 'statusCodes' and forgot to change it in the type definitions
=> 🐛 Fix StatusCode not being used properly

src/components/Dashboard/Modals/EditAppModal/Tabs/IntegrationTab/Components/InputElements/GenericSecretInput.tsx
** Make integration fields required. Removed the clear secret button. **
When selecting an integration the fields for apikey/ password/ ... will now be required, not allowing the user to just skip through them
Could be annoying for integrations that don't have required fields. But they can put anything in the field to satisfy it.
Minor integration styling, bigger tooltips, longer texts, removed clear secret button
=> ✨ Make integrations fields required

src/tools/config/getFrontendConfig.ts
If some apps properties in the config are missing a `value` field or have it set to nothing, it will create a warn in the server console (the docker logs)
=> ✨ Add console warn if apps are missing properties

src/widgets/video/VideoFeed.tsx
This allows the video player to play any video source, including m3u8 live streams, mp4, gifs, etc.
> One of: Bugfix or Feature (Depending on how you view it)
> This change allows the video on a Video Stream widget to be any type of video file. Including gif, mp4, or even m3u8 live streams
> Here is a before and after video showing the change not just working with new video types, but also does not break past functionality.
Before:
https://user-images.githubusercontent.com/39219859/232852017-28107601-2e3f-4930-a280-80e12b8fda67.mp4
After:
https://user-images.githubusercontent.com/39219859/232852084-5bb0afe1-961f-46ef-ac …
=> ✨Allow Video Stream widget to play any video file type.

src/components/Settings/Customization/Theme/ColorSelector.tsx
Bugfix
When going to customization settings, the colors for Primary and Secondary colors are the default colors on refresh. With this fix it ensures that it sets itself to the colors in the config.
**Before**
https://user-images.githubusercontent.com/39219859/234403975-bd28f84c-78ec-476c-92c8-709317ed8198.mp4
**After**
https://user-images.githubusercontent.com/39219859/234404037-c04fcf29-8ecb-4668-91e8-e11cc9adb2b9.mp4
=> 🐛 Make color picker prioritize config colors

next-i18next.config.js, src/tools/language.ts
> One of: Add translation locale
> Added turkish language locale to next-i18next configuration and language select.
> Related issue: #876
=> ✨ Add turkish translation locale

src/components/layout/header/Search.tsx
With this update the search will only be focused when above 768px screen width
=> ✨ Disable search focus on mobile

src/widgets/dnshole/DnsHoleControls.tsx
> Cosmetic
> Rework to permit dnshole controls widget to be reduce in size.
In specific condition down to even 2 by 1 (one dnshole on 1440p screen)
=> 💄 Dns hole controls rework

public/locales/en/modules/bookmark.json, src/widgets/bookmark/BookmarkWidgetTile.tsx
> Cosmetic
> Redesigned the bookmark widget:
> - Take less space per item.
> - Remove the bubble around each items in the vertical and horizontal option to prefer a simple line separator
> - Have the option to hide the Hostname.
> - Have the option to hide the Icon.
> - Completely fill the space available in the widget. (Thanks to @manuel-rw for battling mantine with me on that one)
> - Highlight currently hovered item using user primary shade (at 25% opacity to prevent overdoing it).
> Closes #1035 
> Grid using all the space available:
> Vertical and horizontal underflow stretch:
> Vertical and horizontal overflows:
> All images above also show the highlight function, light/dark theme variation and all links hidden except for radarr.
> Options Hide link
=> 💄 Rework the bookmark widget

public/locales/en/modules/media-requests-stats.json, src/widgets/media-requests/MediaRequestStatsTile.tsx
> Cosmetic
> Media request Stats widget: 
> Made the 3 elements stretch to fit the whole widget.
> Added option to display horizontally or vertically.
> Related issue: #888 
Those are the smallest possible size.
> Horizontal
> ![image](https://github.com/ajnart/homarr/assets/26098587/6db56704-f4f3-4afb-8e8a-332517a45129)
> Vertical
> ![image](https://github.com/ajnart/homarr/assets/26098587/8165de87-74a9-45e2-9e35-5a8d0958d708)
> Options
> ![image](https://github.com/ajnart/homarr/assets/26098587/0acab6b5-94bf-4cfb-8dcd-9576336af557)
=> 💄 Media requests stats widget stretch elements to fit tile

src/tools/server/sdk/plex/plexClient.ts
Feature
During playback, via Plex Session API, within the `MediaContainer` node, music playback appears to be described in `Track` node, whereas Videos appears to be in `Video` node. Within the `Track` node, attribute `type` appears to be set to `track` for various music files I have; as such, I believe using this can be a reasonable detection for audio playback.
Here is a sample response from when playing a file in my music library with actual ID3 and user info redacted:
```
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="1">
<Track addedAt="1678845375" duration="306106" grandparentGuid="plex://artist/5d07bc3440000000000d2780" grandparentKey="/library/metadata/26650" grandparentRatingKey="26650" grandparentThumb="/library/metadata/26650/thumb/1690972605" …
```
=> Adding 'audio' session type for Plex based on 'track' Plex API

src/widgets/calendar/CalendarDay.tsx
> Text in the calendar day used to wrap when the Calendar was seen on mobile in a category. (That is a very, very specific condition)
> Closes issue: #970
=> 🐛 Mobile category calendar day text wrapping

src/config/provider.tsx
Bugfix
The following has an enclosure problem. https://github.com/ajnart/homarr/blob/e755bf6bd0ef97fa225200bfe9073f5fae5b1769/src/config/provider.tsx#L38-L44 
`currentConfig` enclosed in the `useEffect` will be undefined upon the call because it is undefined when the callback is created. We should add `currentConfig` to dependency instead of using `configName`. 
This fixes #1249
=> fix: currentConfig not loaded in useEffect callback

src/widgets/media-server/NowPlayingDisplay.tsx
> One of: Bugfix 
> Movies were forgotten in the "Currently playing" list and showed a default "?" icon.
> Closes #1302
> ![image](https://github.com/ajnart/homarr/assets/26098587/93f42236-50f6-422a-8e05-0f8b379cdefb)
=> 🐛 Added movie in icon list for currently playing

src/tools/server/sdk/plex/plexClient.ts
> Plex tv-shows only shows the epsiode's name, not the series name nor the season like in Jellyfin.
> This PR fixes that. Now plex items look exactly like jellyfin items
> ![image](https://github.com/ajnart/homarr/assets/26098587/f55634fd-f0c6-4732-b0b8-74ca8503d0d0)
=> 🐛 Plex tv-show formatting like jellyfin

src/widgets/bookmark/BookmarkWidgetTile.tsx
> Bugfix 
> Items in bookmark were supposed to stretch to fit widget height. Didn't work in Firefox.
> Before
> ![image](https://github.com/ajnart/homarr/assets/26098587/f09cd50a-2a5b-4622-bc54-3b5eeb342cd7)
> After
> ![image](https://github.com/ajnart/homarr/assets/26098587/4d8a6484-c16c-4855-ba13-819c884fc2a3)
=> 🐛 fix flex for bookmark in firefox

src/widgets/dnshole/DnsHoleSummary.tsx
> Cosmetic
> Adds the text under the percentage blocked on the pihole summary.
> The text already existed in the translation meaning this was a conscious removal at some point.
> I personally think it looks better/more consistent with the text there.
> Closes #1280
> ![image](https://github.com/ajnart/homarr/assets/26098587/34ed6339-a7d4-4bda-8195-35c0f8b8c5ed)
=> 💄 PiHole Summary Percentage Blocked Text

src/components/Settings/Customization/Meta/FaviconChanger.tsx, src/components/Settings/Customization/Meta/LogoImageChanger.tsx, src/components/Settings/Customization/Meta/MetaTitleChanger.tsx, src/components/Settings/Customization/Meta/PageTitleChanger.tsx
> Bugfix
> Trimming caused the user to be unable to write a space character at the end when typing since it was automatically removed.
> Closes #1334
=> 🐛 Page Metadata space char bug

src/pages/_app.tsx, src/widgets/calendar/CalendarTile.tsx, src/widgets/date/DateTile.tsx
> Bugfix
> Locale for dayjs is now based on session's user settings instead of useRouter's locale.
=> 🐛 Fix locale for calendar and clock

public/locales/en/modules/media-requests-list.json, public/locales/en/modules/media-requests-stats.json, src/server/api/routers/media-request.ts, src/widgets/media-requests/MediaRequestListTile.tsx, src/widgets/media-requests/MediaRequestStatsTile.tsx, src/widgets/media-requests/media-request-query.tsx, src/widgets/media-requests/media-request-types.tsx
> Cosmetic / Feature
> Media request widget to show normal media stats (now including total amount of request, decline approved and pending).
> Shows a list of top requester, list length depends on widget total height. The longer the widget get the more users it shows.
> User list cards will grow to always fill all space.
> If there are more than 1 'seerr app, indicators will show which app the user is from.
> Each card directly links to the user profile page on its dedicated 'seerr app (little icon on the left just to clarify to the user).
> 
> Related issue: #1004 
> Closes : #1297 (I also ended up including it [bbb6b20](https://github.com/ajnart/homarr/pull/1344/commits/bbb6b20b3c0497f1da1803dad5c5733d2acc920d) and saw there was an issue relating to that)
> New router query for …
=> ✨ Rework Media Request Stats Widget

public/locales/en/modules/media-requests-list.json, public/locales/en/modules/media-server.json, src/server/api/routers/media-server.ts, src/widgets/media-server/DetailCollapseable.tsx, src/widgets/media-server/MediaServerTile.tsx, src/widgets/media-server/NowPlayingDisplay.tsx
> Bugfix 
> Translate was pointing on the wrong file and translation fields were in the wrong file too. (I don't know what I did there feels like some commit was missing somehow idk).
> Jellyfin has a ton of phantom sessions, including Homarr app that shows in the sessions. filtered those out.
> filter out if there is no current item playing.
> Related issue: #1347
=> 🐛Media Session widget jellyfin sessions + translations

package.json, yarn.lock
> Bugfix / Dependency downgrade
> Reverts nextjs down to 13.4.12 since 13.4.13 and onward breaks things
> Closes #1363
=> ⬇️ next 13.4.19 to 13.4.12

src/widgets/media-requests/MediaRequestListTile.tsx
> Bugfix
> Item was missing the open in new tab field from options.
> Related issue: reported on discord
=> 🐛 Media Request List widget add new tab for item

src/middleware.ts
> Bugfix
> This is a fix for the nextjs dependency not working properly when behind a reverse proxy.
> Code is commented as it is a reference if we ever need to update the dependency and need the fix.
> Also replace rewrite with redirect, so the url updates for the user.
=> 🐛 Nextjs fix for later dependency

Dockerfile
Feature
- Added ``HEALTHCHECK`` to Dockerfile that simply sends a HTTP request to the Entrypoint of Homarr via ``wget`` in spider mode (Intervals are set quite low because Homarr only serves a simple web server with static compiled files)
- Added ``ARG`` for used port in Dockerfile to not have to define multiple times hardcoded (default ``7575``stays the same)
Related issue: #1385 
Dockerfile ``ARG`` for used port added. (Default ``7575``). Makes Dockerfile more maintainable because Port has not to be hardcoded anymore in Dockerfile few times.
``docker ps`` now shows container status as healthy (see above)
=> 🩺  Added healthcheck to image and ARG for port

src/widgets/useNet/UsenetHistoryList.tsx, src/widgets/useNet/UsenetQueueList.tsx
> Cosmetic
> As the torrent widget has a modal, and the usenet widget has a tooltip on hover, this adds an actual modal to the usenet widget on both the queue and the history tabs instead of aforementioned tooltip.
> Modal shows all the infos the widget naturally shows on it's largest setting, providing those information when the widget is too narrow to contain them.
> Target: all modals on tap/click in a popover, for Media-server, Calendar and torrent download
> Related issue: #1348
>![image](https://github.com/ajnart/homarr/assets/26098587/877a0f71-a8df-4928-a903-2b47c4c77416)
> ![image](https://github.com/ajnart/homarr/assets/26098587/89282b15-9f1e-43ac-96a1-434a717259cc)
=> 💄 Added modal for usenet widget

src/widgets/torrent/TorrentQueueItem.tsx
> Cosmetic
> Made the modal popover on click instead of on hover.
> Apply to full row instead of title.
> Restored line highlight on hover.
> Target: all modals on tap/click in a popover, for Media-server, Calendar and torrent download
> Related issue: #1348
> ![image](https://github.com/ajnart/homarr/assets/26098587/86897927-932b-4024-a1b3-7e4e8bc69303)
=> 💄 Change modal for torrent widget

src/widgets/calendar/CalendarDay.tsx
> Cosmetic
> Add the possibility to close the popover when clicking the target to make it behave like a normal popover would.
> Target: all modals on tap/click in a popover, for Media-server, Calendar and torrent download
> Related issue: #1348
=> 💄 Change modal for Calendar

public/locales/en/modules/dns-hole-controls.json, src/widgets/dnshole/DnsHoleControls.tsx
> Feature
> As the badge now is usable to toggle instances of dns-holes, some may find the "toggle all" options to be redundant, especially if you only have one dns-hole.
> This helps make the widget itself take even less space on the dashboard.
> Closes #1382
> 1 by 2 config 
> ![image](https://github.com/ajnart/homarr/assets/26098587/ef762522-d30a-4345-939c-eb5bce1f601b)
> 2 by 2, single instance is centered
> ![image](https://github.com/ajnart/homarr/assets/26098587/c9c35202-deb2-4a8c-b944-d0a76a6cd3ea)
> 2 by 2 with 2 instances spaced evenly
> ![image](https://github.com/ajnart/homarr/assets/26098587/6621071e-1e3a-4171-a37e-eb70dd5e1563)
> With buttons, unchanged
> ![image](https://github.com/ajnart/homarr/assets/26098587/3f8a53ed-6ad9-4a19-ba20-e6b77986b82c)
=> ✨ Hide DNS-Hole control buttons option

src/widgets/calendar/CalendarDay.tsx
> Bugfix
> Calendar indicators would appear on top of the header bar.
> ![image](https://github.com/ajnart/homarr/assets/26098587/e157e10a-a324-4ab4-b500-78ac6bfd8508)
=> 🐛 Calendar indicator over header bar fix

prisma/schema.prisma, public/locales/en/user/preferences.json, src/components/User/Preferences/SearchEngineSelector.tsx, src/components/layout/Templates/BoardLayout.tsx, src/components/layout/Templates/MainLayout.tsx, src/components/layout/header/Header.tsx, src/components/layout/header/Search.tsx, src/pages/user/preferences.tsx, src/server/api/routers/user.ts, src/server/auth.ts, src/validations/user.ts
> Bugfix
> Added search auto-focus property to user preferences. If selected it will automatically focus the search bar on the boards page when accessing it with a desktop device.
> Related issue: #1405
=> Add autofocus for searchbar

src/server/api/routers/download.ts
> Bugfix
> totalDownload is the field used by other integrations for the download speed. Bit of weird naming and made it hard to find.
> It was returning a fixed 0 for nzbget instead of downloadRate.
> Closes #1394
=> 🐛 Download speed widget nzbget fix

src/components/Dashboard/Modals/ChangePosition/ChangePositionModal.tsx
> Bugfix
> Selectors' dropdowns in the "change position" edit menu were cut off.
> Discord report
> Before
> ![image](https://github.com/ajnart/homarr/assets/26098587/dd45707f-f4b0-49b3-b5ed-3acf48cdadf3)
> After
> ![image](https://github.com/ajnart/homarr/assets/26098587/a6c15fa8-65f5-4642-adfb-15b3b7ee9c95)
=> 🐛 Change position selector's dropdown bug

src/components/Dashboard/Tiles/Apps/AppTile.tsx
Bugfix
Change app tile to use `a` component in the button link instead of the `link` component.
#777
=> fix: stop triming traling slashes

src/server/api/routers/config.ts, src/server/api/routers/notebook.ts
*Thank you for contributing to Homarr! So that your Pull Request can be handled effectively, please populate the following fields*
> Bugfix
> Removed usage of disable_edit_mode for notebook and saving config. Replaced it with admin-procedure call
> Related issue: #1305
=> 🐛 Remove DISABLE_EDIT_MODE and replace with admin-procedure

src/widgets/bookmark/BookmarkWidgetTile.tsx, src/widgets/calendar/CalendarTile.tsx, src/widgets/media-requests/MediaRequestListTile.tsx, src/widgets/media-server/MediaServerTile.tsx
> Bugfix
> Reopenning because it got automatically closed after the merge.
> Related issue: #1403
=> 🐛 Fix miscellaneous console errors

data/configs/default.json, src/components/layout/Templates/BoardLayout.tsx
The root app shell has a background color now. Because of that we need to set the background image on it instead of the body. Additionally in the default config was a background image that was added acidentally durring the auth update.
=> 🐛 Background image not visible, remove background image from default config

src/tools/server/sdk/adGuard/adGuard.schema.ts
> Bugfix
> AdGuard schema avg_processing_time can be more than 1. Removing max test.
> https://discord.com/channels/972958686051962910/1167738919761231914
=> 🐛 adguard removed max test on process time

src/widgets/date/DateTile.tsx
> Bugfix
> Upon looking up a problem for one of our get-help issues, I noticed the timezone showing as "(z)" instead of it's named offset. Turns out dayjs needs a plugin to format that and it was forgotten when switching from moment.
to
=> 🐛Clock fix timezone named offset format for dayjs

src/widgets/torrent/TorrentQueueItem.tsx
The torrent speeds are currently displayed in Megabits per second, but @ctrl/shared-torrent is in Bytes. Therefore, they should be displayed in Megabytes per second, as they are only divided by 1024 twice
> Bugfix
> Fix Mb/s / MB/s displayed error
> Related issue: #488
> Difference between qBittorrent and Homarr : (Mio/s = MiB/s ≈ MB/s = 8 Mb/s)
> @ctrl/shared-torrent doc :
> Conversion in Homarr :
=> Fix Mb/s / MB/s conversion error in torrents speed

src/server/api/routers/download.ts
> Bugfix
> For internal ip/urls if the application exists on port 80 or 443. new Url will not set port. So this will add defaults based on protocol for http or https.
> Related issue: #642
> n/a
> n/a
=> feat: add support for default ports on http(s) protocols on download.ts

src/widgets/torrent/TorrentQueueItem.tsx
Use humanFileSize to display Torrent DownloadSpeed and UploadSpeed
> Feature
> Instead of always display Torrent DownloadSpeed and UploadSpeed as MB/s, use humanFileSize to have a better conversion
>
=> Use dynamic conversion for Torrent DownloadSpeed and UploadSpeed

src/widgets/media-requests/MediaRequestListTile.tsx
> Bugfix
> Longer titles will no longer wrap the user.
> Linked to #1423
> ![image](https://github.com/ajnart/homarr/assets/26098587/2b551de8-f25e-486d-8ae6-b68ee8f75f41)
=> 🐛 Media Request wrapping fix with line clamp

public/locales/en/modules/torrents-status.json, src/widgets/torrent/TorrentTile.spec.ts, src/widgets/torrent/TorrentTile.tsx
> Feature
> Add global ratio and filtered torrents list ratio
> Var : widget.properties.displayRatioWithFilter & ratioGlobal & ratioWithFilter
> Function : getTorrentsRatio
The global ratio is calculated using the labels if they are defined
The filtered torrent list ratio is calculated using only the displayed torrents and can be disabled in the widget settings.
=> Add Torrents ratio in Torrents Queue Widget

src/tools/config/getFrontendConfig.ts, src/utils/api.ts
Remove the following
```
Constructing internal hostname address using 5515f208127d 7575
ℹ Requested frontend content of configuration 'default'
Constructing internal hostname address using 5515f208127d 7575
ℹ Requested frontend content of configuration 'default'
Constructing internal hostname address using 5515f208127d 7575
ℹ Requested frontend content of configuration 'default'
Constructing internal hostname address using 5515f208127d 7575
ℹ Requested frontend content of configuration 'default'
Constructing internal hostname address using 5515f208127d 7575
ℹ Requested frontend content of configuration 'default'
Constructing internal hostname address using 5515f208127d 7575
ℹ Requested frontend content of configuration 'default'
Constructing internal hostname address using 5515f208127d …
```
=> 🔇 Remove unnecessary console logs

src/components/layout/Common/Logo.tsx
> Bugfix
> Added height to logo image, Added object fit of contain
> Related issue: #1581
=> 🐛 Logo has no height and object-fit is not contain #1581

src/styles/global.scss
> Bugfix
> Adjust min-width of grid-stack-items
=> 🐛 Placeholder width stretches out of screen

public/locales/en/tools/docker.json
Other: Typo Fix
Found a simple typo in the English locale for the Docker integration and fixed it.
=> Corrected a typo in the Docker integration EN locale

Dockerfile, drizzle/migrate/migrate.ts, drizzle/migrate/package.json, package.json, scripts/run.sh, yarn.lock
> Bugfix
> Adjust Dockerfile and run.sh, Improve migration script logic, Add user homarr to run application
> Related issue:
=> 🐳 Improve dockerfile and start script and fix permission issue

src/components/layout/header/About/Translators.tsx
Bugfix
I fixed a bug that displayed a ```,``` after the last item at ```/manage/about```. I haven't worked with React before, so it could be that there is a better solution but thats my way how I would solve this problem :)
=> :adhesive_bandage: "," after the last language item in the about page

src/components/layout/Common/Logo.tsx
> Bugfix
> Based on @Meierschlumpf changes in #1584, ironing the kink out.
> Unsetting width so only height would matter (Just removing the width wouldn't work as it has a default value to 100%, needs to actively be unset).
> Forcing height to a set value to fit in the header (in this case, just changed to 38 since 50 was too big. Header is 60px, margin top of 10 and padding bottom of 12.)
> Related issue: #1581
=> Header logo size fix

src/widgets/notebook/NotebookEditor.tsx
> Bugfix
> Although non savable, non admin users could go into edit mode.
> Also made ticks unresponsive to non admins as it's supposed to save to config and only admins can do that. (to revisit once the config system changes in the future)
> closes: #1632
=> 🐛 Remove ability to modify text to non admins

src/components/layout/header/Search/MovieModal.tsx
> Bugfix
> Overseerr link was not working at all. Changed to a constructed link. If no overseerr instance found (which should be impossible), will link to TMDB instead.
> Closes #1617
=> 🐛 Overseerr link in search not working fix

src/components/Onboarding/database-not-writeable.tsx, src/pages/onboard.tsx
Fixing the following error:
```
ℹ Instance is using a database on the file system. Checking if file './data/db.sqlite' is writable...
ℹ Database is writeable
ERROR  Database at './data/db.sqlite' has not been mounted: Error: Command failed: mount | grep '/data'
- error Error: Error serializing `.error` returned from `getServerSideProps` in "/onboard".
Reason: `object` ("[object Error]") cannot be serialized as JSON. Please only return JSON serializable data types.
```
=> 🐛 Error object not compatible with json parsing of gssp

drizzle/migrate/package.json
> Bugfix
> Add MIT-License to migrate package.json
> Related issue: #1624
=> 🐛 Migrate package.json has no license field

scripts/run.sh
> Bugfix
> Removes the hardcoded port and allows a custom NEXTAUTH port
> Related to suggestions from https://github.com/truecharts/charts/pull/14563#issuecomment-1811986498
=> Allow custom nextauth port

src/pages/board/[slug]/customize.tsx
> Bugfix
> Save changes affix would overlap the bottom of the custom CSS box, making it impossible to read new lines when writing them
> ![image](https://github.com/ajnart/homarr/assets/26098587/10859f4a-c0f7-4947-8ede-7540855f7f14)
=> 🐛 affix overlapping custom CSS box

src/tools/server/sdk/homeassistant/models/EntityState.ts
> Feature 
> I've added a new possible data type, that can come from HA. This is a problem as many objects have empty attributes, such as TrueNAS integration.
```
{
"attributes": {
"state_class": "measurement",
"attribution": "Data provided by TrueNAS integration",
"Path": "/",
"Status": "ONLINE",
"Healthy": true,
"Is decrypted": true,
"Autotrim": false,
"Scrub state": "FINISHED",
"Scrub start": "1970-01-01T00:00:00+00:00",
"Scrub end": "1970-01-01T00:00:00+00:00",
"Scrub secs left": null,
"Total GiB": 0,
"unit_of_measurement": "GiB",
"icon": "mdi:database-settings",
"friendly_name": "pool free"
},
"entity_id": "sensor.some_entity_id",
"last_changed": "1970-01-01T00:00:00.000Z",
"last_updated": "1970-01-01T00:00:00.000Z",
"state": "999.99"
}
```
=> Updated entityStateSchema to handle nullables

.github/workflows/stale.yml
By default 60 days until an issue or PR is marked as stale.
After that, 7 days until closure:
https://github.com/actions/stale
https://github.com/actions/stale#list-of-input-options
=> 🔧 Configure Stale Action

public/locales/en/modules/media-requests-list.json, src/server/api/routers/media-request.ts, src/widgets/media-requests/MediaRequestListTile.tsx, src/widgets/media-requests/media-request-types.tsx
> Feature
> Added more detailed badges to the media request widget that specify if a request is available or partially available.
> Related issue:  #1793
=> Add availability information about media requests

public/locales/en/modules/dns-hole-controls.json, src/server/api/routers/dns-hole/router.ts, src/widgets/dnshole/DnsHoleControls.tsx
> Bugfix / Security
> 1. Although DNS toggle all controls where hidden, the per item badge was still active.
> 2. Toggle function was not safe from CSS manipulation to regain access to it, made the toggle function only answer to admin users.
> 3. Non admins didn't have controls elements centered.
> Change allow controls to server side.
> Added ability to enable controls for non admins (But still users at least) with widget option.
> Reported in #1685
=> 🐛 Improve admin security over dnshole controls

public/locales/en/manage/boards.json, src/components/Dashboard/Modals/RenameBoard/RenameBoardModal.tsx, src/modals.ts, src/pages/manage/boards/index.tsx, src/server/api/routers/board.ts, src/server/api/routers/config.ts, src/validations/boards.ts
- Adds a button to duplicate a board with a smart algorithm that creates the appropriate config file #1739 
- Adds a rename button that opens a context modal with a text field. Config and properties inside will be renamed properly. #1683
=> feature: board operations

src/server/api/routers/app.ts
Reverts part of #1714 . Related to #1789
=> revert: #1714 migrate to axios.get

src/tools/server/sdk/homeassistant/models/EntityState.ts
Entities with more complex attributes was not supported with the old schema. A light with support for colors have arrays with modes and colors that caused a crash while fetching the entity. This change add support for that sort of entity.
Bugfix
Expanded the entity state model to handle more complex entities.
When adding more complex entities such as lights with color support you get an error. The card shows the red exclamation mark and in the back-end you receive tRPC error about not being able to handle the entity state.
```shell
ERROR  ❌ tRPC failed on smartHomeEntityState.retrieveStatus: Unable to handle Home Assistant entity state. This may be due to malformed response or unknown entity type. Check log for details
```
[Home Assistant Integration] Both type light and type switch don’t …
=> Updated EntityStateSchema for homeassitant

src/widgets/notebook/NotebookEditor.tsx
> Notebook links always opened in new tab after saving.
> Simply add "target" as a saved attribute.
> Discord report
=> 🐛 Notebook link target bug fix

public/locales/en/modules/smart-home/entity-state.json, src/widgets/smart-home/entity-state/entity-state.widget.tsx
Unit of measurement can be chosen to display on the entity card. Friendly name can be used instead of displayName.
Feature
Added options to smart home entity cards to enable the display of unit_of_measurement and friendly name for the entity.
No UI design changes but two switches added to entity card
And the unit of measurement _can_ be added to the card
=> Added features to smart home entitiy card

src/env.js, src/utils/auth/oidc.ts
This new environment variable should allow to configure custom oidc scopes. This is for example useful for oidc with azure ad where the groups scope does not exist and groups are handled in another way
=> feat: add environment variable to overwrite oidc scopes

src/env.js, src/utils/auth/ldap.ts
> Bugfix / Feature
> I've added a new environment variable to define the search scope for ldap
> Closes #1925
> AUTH_LDAP_SEARCH_SCOPE with the options base, one and sub
=> feat: add ldap search scope

public/locales/en/authentication/login.json, src/env.js, src/pages/auth/login.tsx
> One of: Bugfix / Feature
> Incorrectly setting up AUTH_PROVIDER did not make any feedback.
> Added 2 log message:
> - Provider empty: `One or more of the entries for AUTH_PROVIDER could not be parsed and/or returned null.`
> - Unrecognized provider `The value entered for AUTH_PROVIDER "${provider}" is incorrect.`
> Added message on the login page if absolutely no providers entered work.
> ![image](https://github.com/ajnart/homarr/assets/26098587/a376bd01-e6bf-449b-93e8-f050da3fdef8)
=> AUTH_PROVIDER log when incorrect and show error in login page

src/components/Dashboard/Modals/EditAppModal/Tabs/IntegrationTab/Components/InputElements/IntegrationSelector.tsx
> Feature
> Since Emby still uses the same API for our use, and as long as neither stray from their common API points, I have simply added the mention for Emby in the title of the integration for Jellyfin as they are, to a certain extent, the same.
> This is followed by a PR to mention it in the docs, underlying the statement before. https://github.com/homarr-labs/documentation/pull/41
> Please note, This is not a PR to "Add Emby", as this one is already, technically, in. There's is no reason to spend more time on this matter as long as nothing changes.
> Related issue: #1916
=> feat: Mention Emby on Jellyfin integration

README.md
Fixed some death links in the readme, especially for the integrations
=> fix: death links in readme

src/widgets/torrent/TorrentTile.tsx
> Note: lots of lines have changed, it seems my editor is not picking up on the eslint and/or prettier config? If that is indeed the case, any assistance would be greatly appreciated.
Other (perfromance improvement)
Greatly improve rendering performance of large torrent lists by using TanStack Table's (used by `mantine-react-table`) virtualization option.
Using `<MRT_TableContainer />` instead of `<MRT_Table />` to fix container size. This also provides the virtualization service a ref of the scrollview.
As you can see in the video attached below, this also makes the header sticky. I think this is a nice improvement, …
=> ⚡️ Improve TorrentTile rendering performance

src/widgets/torrent/TorrentTile.tsx
> Feature
> Add column ordering in torrent widget
> Related issue: #1831
>
=> Add column ordering in torrent widget

src/server/api/routers/media-request.ts
> Bugfix
> Movie name used the original title instead of translated one.
> TV shows used backdrops as poster, now uses poster as posters
> Closes: #1982
=> fix: change media request TV poster and movie name

src/components/layout/Templates/BoardLayout.tsx
> Bugfix
> Added `playsInline` attribute to `VideoBackground` component to ensure video playback in the background on iOS/Mobil
> N/A
> N/A
> N/A
=> :bug: Added playsInline to VideoBackground

src/components/Board/Customize/Layout/LayoutPreview.tsx, src/components/layout/header/Header.tsx, src/widgets/media-requests/MediaRequestStatsTile.tsx
Just started using Homarr yesterday and noticed this bug #1997
Bugfix
- The z-index of ping indicators is 100 which is the same as the header. Override the z-index to 0.
- Increased header's z-index to 200 to prevent other elements like grid resize handle from floating over it. App tile menus will still float over the header as expected.
**Before fix:**
**After fix:**
Fixes  #1997
Same as #1401
=> Fix ping indicators floating above header in board customization page

src/env.js, src/utils/auth/oidc.ts
Hi Tomas (@ajnart), I have exactly the same issue reported on #1995 , this is a simple fix that can resolve a lot of headaches to the users that want to use OIDC (Because everything can be configured correctly, however if the latency between the service it's not enough will be fail)
Bugfix
if the OIDC provider don't respond in less than 3500ms (Default NextAuth Implementation) the connection fails between Hommar backend and the OIDC provider.
This PR add a new config parameter to increase the timeout using `AUTH_OIDC_TIMEOUT`
https://github.com/ajnart/homarr/issues/1995
- Added AUTH_OIDC_TIMEOUT env variable keeping the same structure as the rest of AUTH_OIDC_XXXX Configs
- I added 4 files related to DevEnv (https://devenv.sh/) to support nix.
No Applicable
=> OIDC Timeout

src/server/api/routers/health-monitoring/proxmox.ts
Surfacing the axios error could help with debugging any issues that might occur with the proxmox api. It was ignored before which I don't think is ideal.
=> Bugfix: Pass axios error into log call for proxmox. Please include in v0.15.3

public/locales/en/modules/torrents-status.json, src/widgets/torrent/TorrentTile.tsx
> One of: Bugfix / UI Refactor
> fix process bar not showing.
> Allow to disable new features to make UI simple.
> Options now allow to make the widget _look_ like it used to before MantineReactTable.
> Made popover show when clicking anywhere on the line instead of just the name cell.
> Added "Added on" column as a showable column.
> (fixed trailing comma on progress)
> Discord report
> closes #1832
> ![image](https://github.com/ajnart/homarr/assets/26098587/900ac33a-5ce8-4c03-b842-490157da6cfb)
=> Torrent widget: polishing UI and improve popover interactions

src/components/layout/header/AvatarMenu.tsx
> bugfix
> 1. Default address with null used to link to "http://i0.wp.com/null" which made the connection insecure. Changed default to 404.
> 2. Use libravatar instead of gravatar. Open-source and proxies gravatar when they don't have it themselves.
> (3. refactored the avatar element a little)
> Closes #1944
=> fix: Avatar host

public/locales/en/modules/smart-home/entity-state.json, src/server/api/routers/smart-home/entity-state.ts, src/tools/server/sdk/homeassistant/HomeAssistant.ts, src/widgets/smart-home/entity-state/entity-state.widget.tsx
Added support for generic toggle on Home Assistant entities that support it. For entities that does not support toggle the feature will silently fail. This way matches how Home Assistant handles it.
> Feature
> Currently when enabling both toggle and automation both will run on click. I am not sure what the best way of handling this is so that it is intuitive for the user. Personally i do not mind if it runs both when you have configured both but I'd love input on this.
> #1848
> Entity toggle switch on the home assistant entity card.
=> Home Assistant entity generic toggle

src/env.js
> Bugfix
> AUTH_OIDC_TIMEOUT is set default to a number but needs a string and thus causes an error.
> Supposed to be fixed already in #2023 but got reverted somehow in #2033.
=> AUTH_OIDC_TIMEOUT make default a string

package.json, src/components/layout/Meta/BoardHeadOverride.tsx, src/components/layout/Meta/CommonHead.tsx
Reference https://nextjs.org/docs/pages/api-reference/components/head#avoid-duplicated-tags
Closes #1676
=> Add `key` for custom favicon

public/locales/en/common.json, public/locales/en/modules/dns-hole-controls.json, src/server/api/routers/dns-hole/router.ts, src/tools/server/sdk/adGuard/adGuard.ts, src/tools/server/sdk/pihole/piHole.ts, src/widgets/dnshole/DnsHoleControls.tsx, src/widgets/dnshole/DnsHoleSummary.tsx, src/widgets/dnshole/TimerModal.tsx
> Feature
> Add timer to disable dns
> Related issue: #2026 
>
=> Feature: Add dns disable timer

src/validations/user.ts
Bugfix
Reuse same validation as for security meter
> Related issue: #2086
=> fix: #2086 enforce password requirements for admin user

src/components/Dashboard/Wrappers/Category/useCategoryActions.tsx
> Bugfix 
> Also marked apps and widgets as affected that are in the wrapper below the category (is also removed)
> Related issue: https://discord.com/channels/972958686051962910/1066060995094646936
=> fix: removing a category hides items from the wrapper below

src/widgets/notebook/NotebookWidgetTile.tsx
Greetings
> Bugfix
> Testing and handling a board with mobile size with 1 column, found that by default the notebook widget requires 2 width columns, causing an overflow on the view and might not be ideal. I get why was implemented in the first place and make sure that as soon that the widget has the appropiate size as soon is created, but maybe is required a better implementation that allow min width columns per screen device? but that's a challenge. For the moment, this will fix the overflow.
Before:
After:
I hope you find it useful.
=> fix: notebook widget overflow on mobile

src/components/layout/header/Search.tsx, src/hooks/useExternalUrl.ts
>  Bugfix 
> When introducing the mentioned PR (see below) that helps write dynamic urls, these dynamic urls were not replaced properly in Search. This PR intends to fix that behavior. It uses the proper hook to rewrite the external url for an `AppType`.
> PR: #2024
=> Bugfix for dynamic urls not properly replaces on Search

src/components/Dashboard/Tiles/Apps/AppTile.tsx
Bugfix
Add rel="noreferrer" to link AppTile.tsx for "Unauthorized" issue with qbittorrent.
Related PR was closed and @ajnart comment mentioned it should be made the default behavior.
https://github.com/ajnart/homarr/pull/2048#issuecomment-2113238216
Related issue: #1933
Issue: https://github.com/ajnart/homarr/issues/1933 
I only edited the file in github, but I havent tested it.
=> Add rel="noreferrer" to link AppTile.tsx

src/components/Dashboard/Tiles/Apps/AppPing.tsx
=> fix: app ping retry interval

src/widgets/dnshole/DnsHoleControls.tsx
> Bugfix: Timer control for individual elements was still apparent to non admin users
> Make button appear only if admin
> Discord Report https://discord.com/channels/972958686051962910/1289780222434086984
=> fix: Make timer button show only to admins

drizzle/migrate/migrate.ts, drizzle/migrate/package.json, package.json, yarn.lock
=> fix: db migration not working

src/server/auth.ts, src/utils/auth/cookies.ts
This pull request should resolve the issue seen by some people using http protocol and a reverse proxy.
**How did I test?**
- I setup a traefik proxy with homarr (copied from #2171) and used it to test my locally created image
- I'll ask people from the issue if they can confirm that the test image, I'll build, fixes there issue.
**What was the cause?**
- Adding the setting for Sessiontoken cookie and AUTH_TRUST_HOST env variable resulted in it using __Secure prefix always, which caused those no longer to work in http environments. See more about cookie prefixes [here](https://datatracker.ietf.org/doc/html/draft-west-cookie-prefixes-05#section-3)
Closes #2171 
Closes https://discord.com/channels/972958686051962910/1300015887230828605
=> fix: credentials login behind proxy no longer works

.vscode/settings.json, src/widgets/dnshole/TimerModal.tsx
>Bugfix
> Prefix that points to translation file was defined not only in the method defintion but also in the method call
> Related issue: #2187 
> No new vars.
> No significant UI changes.
=> fix: remove several occurrences of translation file prefix

src/server/api/routers/media-request.ts, src/widgets/media-requests/MediaRequestListTile.tsx, src/widgets/media-requests/MediaRequestStatsTile.tsx, src/widgets/media-requests/media-request-types.tsx
> Bugfix
> Jellyseerr version 2.0.1 changed rewrite avatarproxy and CachedImage 
Request address changed to add `/avatarproxy`
This prevented the correct user avatar from being requested in the media request component.
Adapting to use older versions of Jellyseerr
> [Related PR](https://github.com/Fallenbagel/jellyseerr/pull/1016)
=> fix: Fix Jellyseerr Avatar Loading Issue

src/server/api/routers/config.ts
> Bugfix
> You can create multiple boards called default as long as the capitalisation is different for each one ('eg 'Default', 'DeFaUlT'), however, when we try to prevent deleting the 'default' board the check is case insensitive and therefore we can't delete these fake default boards. As a side note, I think users should not be allowed to create multiple boards with the same name but different capitalisation in the first place but that seems to be a common theme in other parts of the app.
=> fix: unable to delete boards with capitalised name 'Default'

README.md
Corrected website link for INSTALL in readme.
> Documentation 
> Link for installation in readme that works.
Old link:
New link on install redirects to working page.
=> docs: update readme with correct link for getting started.

README.md
> Documentation : Editing readme
> Fix installation link and add links to all banners
> https://github.com/ajnart/homarr/issues/2261
Just saw the project was moved to homarr-labs, will also PR there.
=> docs: Add links to all banners of readme
